import {
  Banknote,
  Book,
  Box,
  Building,
  Calendar,
  Car,
  CheckSquare,
  Clipboard,
  FileText,
  Flag,
  Folder,
  GraduationCap,
  Handshake,
  Heart,
  Home,
  MapPin,
  MessageSquare,
  Package,
  Repeat,
  ShoppingCart,
  Star,
  Stethoscope,
  StickyNote,
  Ticket,
  Truck,
  Wrench,
  Zap,
  Boxes,
  Briefcase,
  Building2,
  Circle,
  Contact,
  IdCard,
  Landmark,
  CreditCard,
  House,
  LayoutDashboard,
  LifeBuoy,
  Plug,
  ScrollText,
  Settings,
  Share2,
  Smartphone,
  Store,
  ShieldCheck,
  Target,
  UserPlus,
  Users,
  UsersRound,
  type LucideIcon
} from 'lucide-react';

// Server-sent icon keys (access.NavItem.Icon) → components.
const icons: Record<string, LucideIcon> = {
  'layout-dashboard': LayoutDashboard,
  boxes: Boxes,
  'building-2': Building2,
  'users-round': UsersRound,
  'shield-check': ShieldCheck,
  'credit-card': CreditCard,
  'life-buoy': LifeBuoy,
  plug: Plug,
  'scroll-text': ScrollText,
  settings: Settings,
  house: House,
  'user-plus': UserPlus,
  contact: Contact,
  target: Target,
  'check-square': CheckSquare,
  briefcase: Briefcase,
  users: Users,
  landmark: Landmark,
  'id-card': IdCard,
  smartphone: Smartphone,
  store: Store,
  // Object icons (records/objects.go ObjectIcons)
  box: Box,
  handshake: Handshake,
  calendar: Calendar,
  'sticky-note': StickyNote,
  'message-square': MessageSquare,
  repeat: Repeat,
  package: Package,
  folder: Folder,
  star: Star,
  flag: Flag,
  clipboard: Clipboard,
  truck: Truck,
  'graduation-cap': GraduationCap,
  heart: Heart,
  home: Home,
  wrench: Wrench,
  'file-text': FileText,
  ticket: Ticket,
  'shopping-cart': ShoppingCart,
  banknote: Banknote,
  building: Building,
  'map-pin': MapPin,
  car: Car,
  stethoscope: Stethoscope,
  book: Book,
  zap: Zap,
  'share-2': Share2
};

export function navIcon(key: string): LucideIcon {
  return icons[key] ?? Circle;
}
